collections:
  - name: chocolatey.chocolatey
  - name: cisco.ios
  - name: junipernetworks.junos
  - name: community.general
  - name: ansible.windows
roles:
  - name: redhatofficial.rhel7_stig
    version: 0.1.61
  - name: redhatofficial.rhel8_stig
    version: 0.1.60
