---
- name: gather local admin account information
  hosts: windows  
  tasks:
    - name: Shell grab users
      ansible.windows.win_powershell:
        script: |
          Get-LocalGroupMember -Group "Administrators" | Select-Object -Property Name, SID
      register: local_admins

    - name: output users
      ansible.builtin.debug:
        msg: "{{ local_admins | json_query('output[*].Name') }}"
