---
- name: configure VLANs
  hosts: arista
  gather_facts: false
  tasks:
  - name: use vlans resource module
    arista.eos.vlans:
      state: merged
      config:
        - name: desktops
          vlan_id: 50
        - name: servers
          vlan_id: 31
        - name: dog
          vlan_id: 40
        - name: DMZ
          vlan_id: 52
