---
- name: Configure the login banner
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          this is Lou's login banner
          that contains a multiline
          string, as a simple example
        state: present
