---
- name: vlans
  hosts: juniper
  gather_facts: false
  tasks:
    - name: create test vlans
      junipernetworks.junos.junos_vlans:
        state: merged
        config:
          - name: desktops
            vlan_id: 21
          - name: servers
            vlan_id: 30
          - name: printers
            vlan_id: 40
          - name: DMZ
            vlan_id: 50
