---
- name: simple playbook for adding linux users
  hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: add a user
      user:
        name: "{{ user_name }}"
        state: "{{ user_state }}"
        password: "{{ user_password }}"
        
