---
- hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: manage linux services
      ansible.builtin.service: 
        name: "{{ svc_name }}"
        state: "{{ svc_state }}"
        enabled: "{{ svc_enabled }}"
